name: homelab

include:
  - ./compose/homepage.yaml
  - ./compose/portainer.yaml
  - ./compose/beszel.yaml
  - ./compose/uptime-kuma.yaml
  - ./compose/watchtower.yaml
  - ./compose/caddy.yaml
  - ./compose/nextcloud.yaml
  - ./compose/immich.yaml
  - ./compose/jellyfin.yaml
  - ./services/timemachine/compose.yaml
  - ./services/open-webui/compose.yaml
  - ./services/calibre/compose.yaml

networks:
  homelab:
    name: homelab
    driver: bridge
