services:
  uptime-kuma:
    image: louislam/uptime-kuma:2@sha256:c74379ac4509ce2d2c2633f509e67003ee2e45b6e995c5e43fc101f45a0e1fbe
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "${UPTIME_KUMA_PORT:-3001}:3001"
    volumes:
      - /srv/appdata/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - homelab
    labels:
      com.centurylinklabs.watchtower.enable: "false"
